import { expect, test } from '@playwright/test'

async function login(page: import('@playwright/test').Page, name: 'Nanda' | 'Mark' | 'Alisher' = 'Nanda') {
  await page.goto('/')
  if (await page.getByRole('heading', { name: 'Scan From Mobile Chettik' }).isVisible()) {
    await page.getByRole('button', { name: 'Log in using phone number' }).click()
    await page.getByRole('button', { name, exact: true }).click()
    await page.getByRole('textbox', { name: 'Desktop OTP' }).fill('123456')
    await page.getByRole('button', { name: 'Sign in' }).click()
    await expect(page.locator('.chat-head .chat-person strong')).toBeVisible()
    return
  }
  await page.getByRole('button', { name: new RegExp(name) }).click()
  await page.getByPlaceholder('••••••').fill('123456')
  await page.getByRole('button', { name: /verify|подтвердить/i }).click()
  await expect(page.locator('.chat-head .chat-person strong')).toBeVisible()
}

test('seed account sends and edits inside the composer', async ({ page }) => {
  await login(page)
  await page.getByRole('textbox', { name: 'Message text' }).fill('A polished local message')
  await page.getByRole('button', { name: 'Send message' }).click()
  await expect(page.getByText('A polished local message').last()).toBeVisible()
  await page.locator('.message.mine').last().click({ button: 'right' })
  await page.getByText('Edit message', { exact: true }).click()
  await expect(page.getByText('Edit message')).toBeVisible()
  await page.getByRole('textbox', { name: 'Message text' }).fill('Edited without browser dialogs')
  await page.getByRole('button', { name: 'Save message' }).click()
  await expect(page.getByText('Edited without browser dialogs').last()).toBeVisible()
})

test('group info, editing and chat linking are interactive', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name === 'mobile')
  await login(page)
  await page.getByRole('button', { name: /Design circle/ }).click()
  await page.getByRole('button', { name: 'Open group menu' }).click()
  await expect(page.getByRole('button', { name: 'Delete and leave' })).toBeVisible()
  await page.getByRole('button', { name: 'View group info' }).click()
  await expect(page.getByRole('dialog', { name: 'Design circle group info' })).toBeVisible()
  await expect(page.getByText('Group owner')).toBeVisible()
  await page.getByRole('button', { name: 'Manage group' }).click()
  await expect(page.getByRole('dialog', { name: 'Edit group' })).toBeVisible()
  await expect(page.getByText('Group type')).toBeVisible()
  await page.getByRole('button', { name: /Link existing chat/ }).click()
  await expect(page.getByRole('dialog', { name: 'Link existing chat' })).toBeVisible()
  await page.getByPlaceholder('Search chats').fill('Mark')
  await page.locator('.group-link > button').first().click()
  await expect(page.getByRole('dialog', { name: 'Edit group' })).toBeVisible()
})

test('long Mark chat scrolls messages while shell stays visible', async ({ page }, testInfo) => {
  await login(page)
  const composer = page.locator('.compose')
  await page.locator('.messages').evaluate(node => {
    const source = node.querySelector('.message')
    if (!source) throw new Error('Mark chat must contain a message')
    for (let index = 0; index < 32; index += 1) node.append(source.cloneNode(true))
  })
  await expect(composer).toBeVisible()
  const messages = page.locator('.messages')
  await messages.evaluate(node => { node.scrollTop = node.scrollHeight })
  await expect(composer).toBeVisible()
  await expect(page.locator('.chat-head')).toBeVisible()
  if (testInfo.project.name === 'desktop') await expect(page.locator('.sidebar')).toBeVisible()
})

test('settings privacy, devices, language and theme work', async ({ page }, testInfo) => {
  await login(page)
  if (testInfo.project.name === 'mobile') await page.locator('.mobile-nav button').last().click()
  else { await page.getByRole('button', { name: 'Open main menu' }).click(); await page.locator('.main-menu').getByRole('button', { name: 'Settings', exact: true }).click() }
  await page.getByText('Privacy and Security', { exact: true }).click()
  await page.getByText('Last seen & online', { exact: true }).click()
  await page.getByText('Nobody', { exact: true }).click()
  await page.getByRole('button', { name: 'Back' }).click()
  await page.getByText('Devices', { exact: true }).click()
  await expect(page.getByText('Current', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Back' }).click()
  await page.getByText('Appearance', { exact: true }).click()
  await page.getByText('Light', { exact: true }).click()
  await page.getByRole('button', { name: 'Back' }).click()
  await page.getByText('Language', { exact: true }).click()
  await expect(page.locator('.tg-panel-head strong')).toHaveText('Settings')
})

test('admin and legal flows are reachable for permitted roles', async ({ page }, testInfo) => {
  await login(page, 'Mark')
  if (testInfo.project.name === 'desktop') {
    await page.getByTitle('Operations console').click()
    await expect(page.getByText('Moderation console')).toBeVisible()
  }
  test.skip(testInfo.project.name === 'desktop', 'Desktop uses QR-first login; legal links remain in mobile auth')
  await page.goto('/')
  await page.getByText('Terms', { exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Terms of Service' })).toBeVisible()
  await page.goto('/')
  await page.getByText('Privacy', { exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Privacy Policy' })).toBeVisible()
  await page.goto('/')
  await page.getByText('Authors', { exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Authors & Credits' })).toBeVisible()
})

test('mobile layout opens settings and emoji panel', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'mobile', 'Mobile viewport only')
  await login(page, 'Alisher')
  await page.getByRole('button', { name: 'Open emoji picker' }).click()
  await expect(page.getByText('Stickers', { exact: true })).toBeVisible()
  await page.locator('.mobile-nav button').last().click()
  await expect(page.getByText('Privacy and Security', { exact: true })).toBeVisible()
})

test('rich messaging delivers held voice and circle recordings, polls and location', async ({ page }) => {
  await login(page)
  const voiceButton = page.getByRole('button', { name: /Voice mode/ })
  await voiceButton.click()
  const circleButton = page.locator('.voice-button')
  await circleButton.dispatchEvent('pointerdown')
  await page.waitForTimeout(220)
  await expect(page.getByRole('button', { name: /Release to send video circle/ })).toBeVisible()
  await circleButton.dispatchEvent('pointerup')
  await expect(page.getByText('A quiet moment from the studio').last()).toBeVisible()
  await page.getByRole('button', { name: /Circle mode/ }).click()
  await page.getByRole('button', { name: /Voice mode/ }).dispatchEvent('pointerdown')
  await page.waitForTimeout(220)
  await page.getByRole('button', { name: /Release to send voice message/ }).dispatchEvent('pointerup')
  await expect(page.getByText('0:08', { exact: true }).last()).toBeVisible()

  await page.getByRole('button', { name: 'Open rich message tools' }).click()
  await page.getByText('Poll', { exact: true }).click()
  await page.getByRole('button', { name: 'Create poll' }).click()
  await expect(page.getByText('Team sync at 15:00?', { exact: true }).last()).toBeVisible()
  await page.getByRole('button', { name: /Yes, works for me/ }).last().click()

  await page.getByRole('button', { name: 'Open rich message tools' }).click()
  await page.getByText('Location', { exact: true }).click()
  await page.getByRole('button', { name: 'Share location' }).click()
  await expect(page.getByText('Moscow Avenue · precise location').last()).toBeVisible()

  await page.getByRole('button', { name: 'Open rich message tools' }).click()
  await expect(page.getByText('Video circle', { exact: true })).toHaveCount(0)
})

test('stories open and close from the chat shell', async ({ page }, testInfo) => {
  await login(page)
  if (testInfo.project.name === 'mobile') await page.locator('.mobile-stories .story').first().click()
  else await page.locator('.sidebar .story').first().click()
  await expect(page.getByText('This story disappears in 24 hours')).toBeVisible()
  await page.getByRole('button', { name: 'Close story' }).click()
})

test('telegram main menu routes supported Stage 4 entries', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'Desktop menu only')
  await login(page)
  await page.getByRole('button', { name: 'Open main menu' }).click()
  await expect(page.getByText('Chettik Web · v0.5')).toBeVisible()
  await expect(page.getByText('Wallet', { exact: true })).toHaveCount(0)
  await page.getByText('New Group', { exact: true }).click()
  await expect(page.getByRole('heading', { name: 'New Group' })).toBeVisible()
  await page.getByRole('button', { name: 'Back to main menu' }).click()
  await page.getByText('Night Mode', { exact: true }).click()
  await expect(page.locator('.app')).not.toHaveClass(/dark/)
  await page.locator('.main-menu').getByRole('button', { name: 'Settings', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Settings' })).toBeVisible()
})

test('my profile and saved messages target the signed-in account', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'Desktop menu only')
  await login(page, 'Nanda')
  await page.getByRole('button', { name: 'Open main menu' }).click()
  await page.getByRole('button', { name: 'My Profile', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Nanda profile' })).toBeVisible()
  await page.getByRole('button', { name: 'Close profile' }).click()

  await page.getByRole('button', { name: 'Open main menu' }).click()
  await page.getByRole('button', { name: 'Saved Messages', exact: true }).click()
  await expect(page.locator('.chat-row.active').last()).toContainText('Saved Messages')
  await expect(page.getByText('Messages saved for yourself')).toBeVisible()
  await expect(page.locator('.messages .message')).toContainText('Remember to write this down.')
})

test('phone privacy Nobody removes the Mobile row for viewers', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'Desktop profile treatment')
  await page.goto('/')
  await page.evaluate(async () => {
    const challenge = await fetch('http://127.0.0.1:8787/api/auth/otp/request', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ phone: '+22222222222' }) })
    const { challengeId } = await challenge.json()
    const auth = await fetch('http://127.0.0.1:8787/api/auth/otp/verify', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ phone: '+22222222222', code: '123456', challengeId }) })
    const { token } = await auth.json()
    await fetch('http://127.0.0.1:8787/api/me/profile', { method: 'PATCH', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ privacy: { phone: 'Nobody' } }) })
  })
  await login(page, 'Nanda')
  await page.getByRole('button', { name: 'Open Mark profile' }).first().click()
  await expect(page.getByRole('dialog', { name: 'Mark profile' }).getByText('Mobile', { exact: true })).toHaveCount(0)
})

test('profile, confirmations and chat context actions are interactive', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'Context menus are desktop treatment')
  await login(page)
  await page.getByRole('button', { name: 'Open Mark profile' }).first().click()
  await expect(page.getByRole('dialog', { name: 'Mark profile' })).toBeVisible()
  await page.getByRole('button', { name: 'More profile actions' }).click()
  await expect(page.getByText('Export chat', { exact: true })).toBeVisible()
  await page.getByText('Block user', { exact: true }).last().click()
  await expect(page.getByRole('dialog', { name: 'Block Mark?' })).toBeVisible()
  await page.getByRole('button', { name: 'Cancel' }).click()

  await page.locator('.sidebar .chat-row').first().click({ button: 'right' })
  await expect(page.getByRole('menu')).toBeVisible()
  await page.getByText('Pin', { exact: true }).click()
  await expect(page.locator('.sidebar .chat-row svg')).toHaveCount(1)
  await page.locator('.message').first().click({ button: 'right' })
  await expect(page.getByText('Copy text', { exact: true })).toBeVisible()
  await page.getByText('Forward', { exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Forward to' })).toBeVisible()
  await page.getByRole('dialog', { name: 'Forward to' }).getByText('Saved Messages', { exact: true }).click()

  await page.getByRole('button', { name: 'Open main menu' }).click()
  await page.getByRole('button', { name: 'Saved Messages', exact: true }).click()
  await expect(page.locator('.messages .message').filter({ hasText: 'I tried the new onboarding flow.' })).toBeVisible()
})

test('starts a device-local secret chat and selects timed media', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'Desktop profile treatment')
  await login(page)
  await page.getByRole('button', { name: 'Open Mark profile' }).first().click()
  await page.getByRole('button', { name: 'More profile actions' }).click()
  await page.getByRole('button', { name: 'Start secret chat' }).first().click()
  await expect(page.getByText('Secret chat · Mark', { exact: true }).first()).toBeVisible()
  await page.locator('input[type="file"]').setInputFiles({ name: 'private.jpg', mimeType: 'image/jpeg', buffer: Buffer.from('image') })
  await expect(page.getByRole('dialog', { name: 'Media send options' })).toBeVisible()
  await page.getByRole('button', { name: 'Set media timer' }).click()
  await page.getByRole('button', { name: 'View Once' }).click()
  await page.getByRole('button', { name: 'Send media' }).click()
  await expect(page.getByText('1 · View once')).toBeVisible()
})
