import { ArrowLeft, Camera, Check, ChevronRight, ContactRound, Fingerprint, KeyRound, Laptop, Languages, LockKeyhole, Mail, MonitorSmartphone, Moon, QrCode, ScanLine, Smartphone, Sun, Timer, UserRound, Volume2, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import type { Account, Audience, Profile } from './Chettik'

type Device = { id: string; label: string; last_seen: string }
type Props = { account: Account; profile: Profile; setProfile: (profile: Profile) => void; token: string; dark: boolean; setDark: (value: boolean) => void; language: 'EN' | 'RU'; onLanguage: () => void; onClose: () => void; onLogout: () => void }
type Panel = 'main' | 'privacy' | 'security' | 'devices' | 'qr' | 'appearance' | 'profile'
const labels: Record<string, string> = { phone: 'Phone number', lastSeen: 'Last seen & online', photo: 'Profile photos', bio: 'Bio', birthday: 'Birthday', forwards: 'Forwarded messages', voice: 'Voice messages', messages: 'Messages' }
const API_URL = 'http://127.0.0.1:8787/api'

export function SettingsDrawer({ account, profile, setProfile, token, dark, setDark, language, onLanguage, onClose, onLogout }: Props) {
  const [panel, setPanel] = useState<Panel>('main')
  const [audienceKey, setAudienceKey] = useState('lastSeen')
  const [devices, setDevices] = useState<Device[]>([])
  const [confirmTerminateOthers, setConfirmTerminateOthers] = useState(false)
  useEffect(() => {
    if (!token) return
    fetch(`${API_URL}/me/devices`, { headers: { Authorization: `Bearer ${token}` } })
      .then(response => response.ok ? response.json() : [])
      .then(setDevices)
      .catch(() => setDevices([]))
  }, [token])
  const set = (patch: Partial<Profile>) => setProfile({ ...profile, ...patch })
  const setAudience = (key: string, value: Audience) => set({ privacy: { ...profile.privacy, [key]: value } })
  const row = (icon: React.ReactNode, title: string, value: string, action: () => void) => <button className="tg-row" onClick={action}><span className="tg-row-icon">{icon}</span><span className="tg-row-copy"><strong>{title}</strong><small>{value}</small></span><ChevronRight size={19} /></button>
  const title = panel === 'main' ? 'Settings' : panel === 'privacy' ? 'Privacy and Security' : panel === 'security' ? 'Account security' : panel === 'devices' ? 'Devices' : panel === 'qr' ? 'My QR code' : panel === 'appearance' ? 'Appearance' : 'Edit profile'
  return <div className="tg-overlay" role="dialog" aria-modal="true" aria-label={title}>
    <aside className="tg-panel">
      <header className="tg-panel-head"><button className="icon-btn" aria-label={panel === 'main' ? 'Close settings' : 'Back'} onClick={() => panel === 'main' ? onClose() : setPanel('main')}>{panel === 'main' ? <X size={21} /> : <ArrowLeft size={21} />}</button><strong>{title}</strong></header>
      {panel === 'main' && <><button className="tg-profile" onClick={() => setPanel('profile')}><span className="avatar profile-avatar" style={{ background: account.color }}>{account.initials}</span><span><strong>{account.name}</strong><small>{account.phone}</small><small>{account.username}</small></span><ChevronRight size={19} /></button><div className="tg-section">Settings</div><div className="tg-list">
        {row(<LockKeyhole size={19} />, 'Privacy and Security', 'Blocked users, passcode, devices', () => setPanel('privacy'))}
        {row(<MonitorSmartphone size={19} />, 'Devices', `${devices.length} active session${devices.length === 1 ? '' : 's'}`, () => setPanel('devices'))}
        {row(<Languages size={19} />, 'Language', language === 'RU' ? 'Русский' : 'English', onLanguage)}
        {row(dark ? <Moon size={19} /> : <Sun size={19} />, 'Appearance', dark ? 'Dark theme' : 'Light theme', () => setPanel('appearance'))}
      </div><div className="tg-section">Chettik</div><div className="tg-list">{row(<QrCode size={19} />, 'My QR code', 'Share your profile safely', () => setPanel('qr'))}</div><button className="tg-danger" onClick={onLogout}>Log out</button></>}
      {panel === 'profile' && <div className="tg-form"><div className="avatar edit-avatar" style={{ background: account.color }}>{account.initials}</div><label>Name<input value={account.name} readOnly /></label><label>Bio<textarea value={profile.bio} onChange={e => set({ bio: e.target.value })} placeholder="Add a few words about yourself" /></label><label>Username<input value={account.username} readOnly /></label><label>Discord<input value={profile.discord} onChange={e => set({ discord: e.target.value })} placeholder="Optional" /></label><label>GitHub<input value={profile.github} onChange={e => set({ github: e.target.value })} placeholder="Optional" /></label></div>}
      {panel === 'privacy' && <><p className="tg-help">Control what other people can see about you and how they can contact you.</p><div className="tg-list">{Object.entries(labels).map(([key, value]) => row(key === 'phone' ? <ContactRound size={19} /> : key === 'photo' ? <Camera size={19} /> : key === 'voice' ? <Volume2 size={19} /> : <UserRound size={19} />, value, profile.privacy?.[key] === 'Contacts' ? 'My contacts' : profile.privacy?.[key] || 'Everybody', () => { setAudienceKey(key); setPanel('security') }))}</div><div className="tg-section">Account protection</div><div className="tg-list">{row(<KeyRound size={19} />, 'Two-Step Verification', profile.twoStep ? 'Password is set' : 'Add a password', () => set({ twoStep: !profile.twoStep }))}{row(<Fingerprint size={19} />, 'Passcode and biometrics', profile.passcode ? 'Enabled' : 'Off', () => set({ passcode: !profile.passcode, biometrics: !profile.passcode }))}{row(<Mail size={19} />, 'Login email', profile.loginEmail || 'Not set', () => set({ loginEmail: profile.loginEmail ? '' : account.email }))}{row(<Timer size={19} />, 'Delete my account if away', profile.autoDelete || '6 months', () => set({ autoDelete: profile.autoDelete === '1 year' ? '6 months' : '1 year' }))}</div></>}
      {panel === 'security' && <AudienceSheet name={labels[audienceKey]} value={profile.privacy?.[audienceKey] || 'Everybody'} exceptions={profile.privacyExceptions?.[audienceKey]} onChange={value => setAudience(audienceKey, value)} onExceptions={() => set({ privacyExceptions: { ...profile.privacyExceptions, [audienceKey]: { always: ['Nanda'], never: ['Mark'] } } })} />}
      {panel === 'devices' && <><button className="tg-danger" onClick={() => setConfirmTerminateOthers(true)}>{language === 'RU' ? 'Завершить другие сеансы' : 'Terminate other sessions'}</button>{confirmTerminateOthers && <div className="confirm-backdrop" role="dialog" aria-modal="true" aria-label={language === 'RU' ? 'Завершить другие сеансы?' : 'Terminate other sessions?'}><div className="confirm-card"><h2>{language === 'RU' ? 'Завершить другие сеансы?' : 'Terminate other sessions?'}</h2><p>{language === 'RU' ? 'Все устройства, кроме текущего, выйдут из Chettik. Вы сможете войти снова с подтверждением номера.' : 'Every device except this one will be signed out of Chettik. You can sign in again with phone verification.'}</p><div className="confirm-actions"><button onClick={() => setConfirmTerminateOthers(false)}>{language === 'RU' ? 'Отмена' : 'Cancel'}</button><button className="destructive" onClick={() => { void fetch(`${API_URL}/me/sessions/revoke-others`, { method: 'POST', headers: { Authorization: `Bearer ${token}` } }).then(response => response.ok ? fetch(`${API_URL}/me/devices`, { headers: { Authorization: `Bearer ${token}` } }).then(next => next.json()).then(setDevices) : undefined).finally(() => setConfirmTerminateOthers(false)) }}>{language === 'RU' ? 'Завершить' : 'Terminate'}</button></div></div></div>}</>}
      {panel === 'devices' && <><p className="tg-help">These devices are logged into your Chettik account. End sessions you do not recognize.</p><button className="tg-qr-button" onClick={() => setPanel('qr')}><ScanLine size={21} />Link desktop device with QR</button><div className="tg-section">Active sessions</div><div className="tg-list">{devices.map((device, index) => <div className="tg-device" key={device.id}><>{index === 0 ? <Laptop size={21} /> : index === 1 ? <Smartphone size={21} /> : <MonitorSmartphone size={21} />}</><span><strong>{device.label}</strong><small>Last active {new Date(device.last_seen).toLocaleString()}</small></span>{index === 0 ? <em>Current</em> : <button onClick={() => fetch(`${API_URL}/me/devices/${device.id}`, { method: 'DELETE', headers: { Authorization: `Bearer ${token}` } }).then(() => setDevices(current => current.filter(item => item.id !== device.id)))}>Terminate</button>}</div>)}</div></>}
      {panel === 'qr' && <div className="qr-page"><div className="qr-code"><QrCode size={148} strokeWidth={1.3} /><span>CHETTIK</span></div><h3>@{account.username.replace('@', '')}</h3><p>Let people scan this code to open your profile. It does not expose your phone number.</p></div>}
      {panel === 'appearance' && <div className="tg-list"><button className="tg-row" onClick={() => setDark(false)}><span className="tg-row-icon"><Sun size={19} /></span><span className="tg-row-copy"><strong>Light</strong><small>Clean light palette</small></span>{!dark && <Check size={18} />}</button><button className="tg-row" onClick={() => setDark(true)}><span className="tg-row-icon"><Moon size={19} /></span><span className="tg-row-copy"><strong>Dark</strong><small>Comfortable in low light</small></span>{dark && <Check size={18} />}</button></div>}
    </aside>
  </div>
}

function AudienceSheet({ name, value, exceptions, onChange, onExceptions }: { name: string; value: Audience; exceptions?: { always: string[]; never: string[] }; onChange: (v: Audience) => void; onExceptions: () => void }) {
  return <div className="audience-sheet"><p className="tg-help">Who can see your {name.toLowerCase()}?</p>{([['Everybody', 'Everyone can see it'], ['Contacts', 'Only people in your contacts'], ['Nobody', 'Hidden from everyone']] as [Audience, string][]).map(([choice, hint]) => <button className="audience-choice" key={choice} onClick={() => onChange(choice)}><span className={`radio ${value === choice ? 'selected' : ''}`} /> <span><strong>{choice === 'Contacts' ? 'My contacts' : choice}</strong><small>{hint}</small></span></button>)}<div className="tg-section">Add exceptions</div><button className="exception-row" onClick={onExceptions}><span><strong>Always allow</strong><small>{exceptions?.always?.join(', ') || 'Add users'}</small></span><ChevronRight size={19} /></button><button className="exception-row" onClick={onExceptions}><span><strong>Never allow</strong><small>{exceptions?.never?.join(', ') || 'Add users'}</small></span><ChevronRight size={19} /></button></div>
}
